# Generated by Django 3.2.6 on 2021-08-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thanos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='featurerequest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='featurerequestresponse',
            name='display_status',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='featurerequestresponse',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='useractions',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
