# Generated by Django 3.2.6 on 2021-08-29 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thanos', '0002_auto_20210825_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='featurerequest',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='featurerequestresponse',
            name='feature_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='thanos.featurerequest'),
        ),
        migrations.AlterField(
            model_name='featurerequestresponse',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('text', models.TextField()),
                ('feature_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='thanos.featurerequest')),
                ('parent_comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='thanos.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
