export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';
export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_IN = 'SIGN_IN';

export const GET_FEATURES_REQUEST = 'GET_FEATURES_REQUEST'
export const GET_FEATURES_SUCCESS = 'GET_FEATURES_SUCCESS'
export const GET_FEATURES_ERROR = 'GET_FEATURES_ERROR'

export const CREATE_FEATURE_REQUEST = 'CREATE_FEATURE_REQUEST'
export const CREATE_FEATURE_SUCCESS = 'CREATE_FEATURE_SUCCESS'
export const CREATE_FEATURE_ERROR = 'CREATE_FEATURE_ERROR'

export const FEATURE_DETAILS_REQUEST = 'FEATURE_DETAILS_REQUEST'
export const FEATURE_DETAILS_SUCCESS = 'FEATURE_DETAILS_SUCCESS'
export const FEATURE_DETAILS_ERROR = 'FEATURE_DETAILS_ERROR'