export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';
export const SIGN_OUT = 'SIGN_OUT';

export const GET_FEATURES_REQUEST = 'GET_FEATURES_REQUEST'
export const GET_FEATURES_SUCCESS = 'GET_FEATURES_SUCCESS'
export const GET_FEATURES_ERROR = 'GET_FEATURES_ERROR'

export const CREATE_FEATURE_REQUEST = 'CREATE_FEATURE_REQUEST'
export const CREATE_FEATURE_SUCCESS = 'CREATE_FEATURE_SUCCESS'
export const CREATE_FEATURE_ERROR = 'CREATE_FEATURE_ERROR'

export const FEATURE_DETAILS_REQUEST = 'FEATURE_DETAILS_REQUEST'
export const FEATURE_DETAILS_SUCCESS = 'FEATURE_DETAILS_SUCCESS'
export const FEATURE_DETAILS_ERROR = 'FEATURE_DETAILS_ERROR'

export const USER_FEATURES_REQUEST = 'USER_FEATURES_REQUEST'
export const USER_FEATURES_SUCCESS = 'USER_FEATURES_SUCCESS'
export const USER_FEATURES_ERROR = 'USER_FEATURES_ERROR'

export const WATCH_REQUEST = 'WATCH_REQUEST'
export const WATCH_SUCCESS = 'WATCH_SUCCESS'
export const WATCH_ERROR = 'WATCH_ERROR'

export const UPVOTE_REQUEST = 'UPVOTE_REQUEST'
export const UPVOTE_SUCCESS = 'UPVOTE_SUCCESS'
export const UPVOTE_ERROR = 'UPVOTE_ERROR'

export const CREATE_COMMENT_REQUEST = 'CREATE_COMMENT_REQUEST'
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS'
export const CREATE_COMMENT_ERROR = 'CREATE_COMMENT_ERROR'

export const GET_ALL_COMMENT_REQUEST = 'GET_ALL_COMMENT_REQUEST'
export const GET_ALL_COMMENT_SUCCESS = 'GET_ALL_COMMENT_SUCCESS'
export const GET_ALL_COMMENT_ERROR = 'GET_ALL_COMMENT_ERROR'

export const WATCH_CLICK_REQUEST = 'WATCH_CLICK_REQUEST'
export const WATCH_CLICK_SUCCESS = 'WATCH_CLICK_SUCCESS'
export const WATCH_CLICK_ERROR = 'WATCH_CLICK_ERROR'

export const UNWATCH_CLICK_REQUEST = 'UNWATCH_CLICK_REQUEST'
export const UNWATCH_CLICK_SUCCESS = 'UNWATCH_CLICK_SUCCESS'
export const UNWATCH_CLICK_ERROR = 'UNWATCH_CLICK_ERROR'

export const UPVOTE_CLICK_REQUEST = 'UPVOTE_CLICK_REQUEST'
export const UPVOTE_CLICK_SUCCESS = 'UPVOTE_CLICK_SUCCESS'
export const UPVOTE_CLICK_ERROR = 'UPVOTE_CLICK_ERROR'

export const DOWNVOTE_CLICK_REQUEST = 'DOWNVOTE_CLICK_REQUEST'
export const DOWNVOTE_CLICK_SUCCESS = 'DOWNVOTE_CLICK_SUCCESS'
export const DOWNVOTE_CLICK_ERROR = 'DOWNVOTE_CLICK_ERROR'

export const FEATURE_RESPONSE_REQUEST = 'FEATURE_RESPONSE_REQUEST'
export const FEATURE_RESPONSE_SUCCESS = 'FEATURE_RESPONSE_SUCCESS'
export const FEATURE_RESPONSE_ERROR = 'FEATURE_RESPONSE_ERROR'

export const DELETE_FEATURE_REQUEST = 'DELETE_FEATURE_REQUEST'
export const DELETE_FEATURE_SUCCESS = 'DELETE_FEATURE_SUCCESS'
export const DELETE_FEATURE_ERROR = 'DELETE_FEATURE_ERROR'

export const SEARCH_FEATURE_REQUEST = 'SEARCH_FEATURE_REQUEST'
export const SEARCH_FEATURE_SUCCESS = 'SEARCH_FEATURE_SUCCESS'
export const SEARCH_FEATURE_ERROR = 'SEARCH_FEATURE_ERROR'