export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';
export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_IN = 'SIGN_IN';

export const GET_FEATURES_REQUEST = 'GET_FEATURES_REQUEST'
export const GET_FEATURES_SUCCESS = 'GET_FEATURES_SUCCESS'
export const GET_FEATURES_ERROR = 'GET_FEATURES_ERROR'

export const CREATE_FEATURE_REQUEST = 'CREATE_FEATURE_REQUEST'
export const CREATE_FEATURE_SUCCESS = 'CREATE_FEATURE_SUCCESS'
export const CREATE_FEATURE_ERROR = 'CREATE_FEATURE_ERROR'

export const FEATURE_DETAILS_REQUEST = 'FEATURE_DETAILS_REQUEST'
export const FEATURE_DETAILS_SUCCESS = 'FEATURE_DETAILS_SUCCESS'
export const FEATURE_DETAILS_ERROR = 'FEATURE_DETAILS_ERROR'

export const USER_FEATURES_REQUEST = 'USER_FEATURES_REQUEST'
export const USER_FEATURES_SUCCESS = 'USER_FEATURES_SUCCESS'
export const USER_FEATURES_ERROR = 'USER_FEATURES_ERROR'

export const WATCH_REQUEST = 'WATCH_REQUEST'
export const WATCH_SUCCESS = 'WATCH_SUCCESS'
export const WATCH_ERROR = 'WATCH_ERROR'

export const UPVOTE_REQUEST = 'UPVOTE_REQUEST'
export const UPVOTE_SUCCESS = 'UPVOTE_SUCCESS'
export const UPVOTE_ERROR = 'UPVOTE_ERROR'

export const CREATE_COMMENT_REQUEST = 'CREATE_COMMENT_REQUEST'
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS'
export const CREATE_COMMENT_ERROR = 'CREATE_COMMENT_ERROR'

export const GET_ALL_COMMENT_REQUEST = 'GET_ALL_COMMENT_REQUEST'
export const GET_ALL_COMMENT_SUCCESS = 'GET_ALL_COMMENT_SUCCESS'
export const GET_ALL_COMMENT_ERROR = 'GET_ALL_COMMENT_ERROR'